### ISSUE TITLE
検索できるようにする

### ISSUE THREAD

**Issue by valjapan** [yukiyuki961/GitHubCliant#9]

**Comment by valjapan** [comment]
@omuomugin
https://developer.github.com/v3/search/
これでOK?

**Comment by omuomugin** [comment]
そうそう
そのうちでこれ

```
https://api.github.com/search/repositories?q=<検索ワード>+language:<言語>&sort=stars&order=desc
```

GitHubApiのところに

```
@Get("https://api.github.com/search/repositories?q={search_word}&sort=stars&order=desc")
fun searchRepositories(@Query("search_word") searchWord: String): Observable<Repositories>

// search_wordはq=<検索ワード>+language:<言語>みたいな形にしてからsearchWordに渡す
``

**Comment by valjapan** [comment]
@omuomugin 言語のソートってことですよね、ってことは、タブ？みたいに選択する欄が必要ですよね？

**Comment by omuomugin** [comment]
言語のソートっていうか、たとえばsearchWordに
"android+lanuage:kotlin"って文字列渡したら、androidっていう検索かつkotlinで絞ってくれる

**Comment by valjapan** [comment]
@omuomugin 結局Daialogの通知みたいに一つ選択する欄ないと検索できないってことですよね？
名前が思い出せないけど、押すとしたに伸びて一つ選ぶやつ（ソートとかによく出てくる

**Comment by omuomugin** [comment]
あーそうそう。
スピナーね。うんうん。

**Comment by valjapan** [comment]
@omuomugin SearchViewってのを見つけたんですけど、EditTextとButtonを使うのとどっちがいいのでしょう

**Comment by omuomugin** [comment]
EditTextとButton使うのがいい

**Comment by valjapan** [comment]
@omuomugin SpinnerをMainActivityでarreysに書いたItemを取得するJavaでよくあるやつ、Kotlinだとどうなるのでしょうか

**Comment by omuomugin** [comment]
```
// 変数宣言
Spinner spinner;

...

// spinnerを探す
spinner = findViewById(R.id.spinner) as Spinner

...

// adapterをセットする
val list: List<String> = mutableListOf("Java", "Kotlin", "Ruby")
adapter: ArrayAdapter<String> = ArrayAdapter<String>(this, android.R.layout.simple_list_item, list)
adapter.dropDownViewResources(android.R.layout.simple_spinner_dropdown_item)
spinner.adapter = adapter
```

こういう感じか。

**Comment by valjapan** [comment]
`Spinner spinner;`
ってJavaじゃないですかね

**Comment by valjapan** [comment]
@omuomugin 
` private var spinner: Spinner by Delegates.notNull()`
とか？

**Comment by valjapan** [comment]
@omuomugin  arrays.xmlに書いたのってあとあとそっちに直すこと可能ですよね？

**Comment by omuomugin** [comment]
あ、それJavaだわ笑
それそれ

**Comment by omuomugin** [comment]
直せるけど、最初からlistで書いちゃったほうが楽だよ

**Comment by valjapan** [comment]
@omuomugin 普通にadapterセットで赤字出るんですよねー

**Comment by valjapan** [comment]
@omuomugin listに書きます。

**Comment by valjapan** [comment]
@omuomugin 
`adapter: ArrayAdapter<String> = ArrayAdapter<String>(this, android.R.layout.simple_list_item, list)`
ここでエラーが起きます

**Comment by valjapan** [comment]
@omuomugin あれ、書く場所の確認してないけど、勝手にMainActivityのOnCreateに書いちゃってるんですけど、いいんでしたっけ

**Comment by omuomugin** [comment]
どこで出てる？
スクショとか貼ってもらえると

**Comment by yukiyuki961** [comment]
![Uploading screenshot 2017-02-05 22.34.14.png…]()

**Comment by valjapan** [comment]
<img width="1440" alt="screenshot 2017-02-05 22 34 14" src="https://cloud.githubusercontent.com/assets/19369026/22626562/64f41e84-ebf3-11e6-939a-ca4504460a87.png">

**Comment by valjapan** [comment]
あ、Code多いのは仕様です、最初はJavaとKotlinとSwiftだけで実験します

**Comment by omuomugin** [comment]
あ、adapterにvalつけるの忘れてた

```
val adapter: ArrayAdapter<String> = ArrayAdapter<String>(this, android.R.layout.simple_list_item, list)
```

**Comment by valjapan** [comment]
<img width="1440" alt="screenshot 2017-02-05 22 42 05" src="https://cloud.githubusercontent.com/assets/19369026/22626588/62faee54-ebf4-11e6-8371-050c176d9783.png">

simple_list_itemってどこを指しているのでしょう？
あとdropDownViewResourcesでのエラーです

**Comment by omuomugin** [comment]
simple_list_itemはandroidにデフォルトで入ってるやつだからandroid.R.siくらいまで打ってそれっぽいのを使って

dropDpwnVIewResourcesはもしかしたら、adapter.setDropDownResources()呼ばないとかも

**Comment by valjapan** [comment]
simple_list_itemはsimple_list_item_1というので他のコードで使用していたので多分これでいいと思います。
`adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)`
エラーこれで改善なりました

**Comment by valjapan** [comment]
成功しました、また何かあったら連絡します。いつでも返信ください。

**Comment by omuomugin** [comment]
おっけー！

**Comment by valjapan** [comment]
<img width="1440" alt="screenshot 2017-02-05 23 25 14" src="https://cloud.githubusercontent.com/assets/19369026/22626896/7a1cb80a-ebfa-11e6-9fd9-0a76dd3fc21a.png">

search部分のsubscribe入れようとしています。OnCreate部分を少し真似したんですけどどうしてもxでエラーが起きます

**Comment by omuomugin** [comment]
あ、ごめん

```
@Get("https://api.github.com/search/repositories?q={search_word}&sort=stars&order=desc")
fun searchRepositories(@Query("search_word") searchWord: String): Observable<List<Repositories>>
```

ここObservable<Repositories>じゃなくてObservable<List<Repositories>>だごめん。

**Comment by valjapan** [comment]
<img width="496" alt="screenshot 2017-02-06 8 28 17" src="https://cloud.githubusercontent.com/assets/19369026/22630932/86828772-ec46-11e6-87e1-19cca9669352.png">

Srarchの部分の検索方法、どうしたらいいでしょうか、OnClickLisnerで呼び出しまでは作りましたが、EditTextとsortの改良もしましたが、こんな感じでしょうか
` @GET("https://api.github.com/search/repositories?q={search_word}&s{sort}=stars&order=desc")
    fun searchRepositories(@Query("search_word") searchWord: String,@Query("sort")sort:String):Observable<List<Repositories>>`

**Comment by valjapan** [comment]
@omuomugin スクショ部分はArticleActivity内です

**Comment by omuomugin** [comment]
```
@GET("https://api.github.com/search/repositories?q={search_word}&sort={sort}&order=desc") fun searchRepositories(@Query("search_word") searchWord: String,@Query("sort")sort:String):Observable<List<Repositories>>
```

かなー。sortのところがちょっと違う。

あとこの処理は、ArticleActivity内じゃないんじゃないかな？
リポジトリー一覧を見るを取得するんだからリポジトリ一覧のとこじゃない？

**Comment by valjapan** [comment]
@omuomugin 
[https://github.com/yukiyuki961/GitHubClient/tree/HelpMe](url)
branch切ってなんとか自力でやってみましたがどうにもエラーが治らなくてどうしたらいいか困ってます。
DLしてここ違うとか指摘していただければ幸いです

**Comment by omuomugin** [comment]
バグの箇所はなんとなくわかったからちょっとまってて。

**Comment by valjapan** [comment]
@omuomugin まだ無理そうですか？

**Comment by valjapan** [comment]
急ぎではないですが。

**Comment by valjapan** [comment]
@omuomugin 進捗どうですかー

**Comment by omuomugin** [comment]
@yukiyuki961 進捗よくないでーす。
土曜日になりそう。

**Comment by valjapan** [comment]
@omuomugin それでは土曜日によろしくお願いします。

**Comment by valjapan** [comment]
@omuomugin 
検索機能、いろいろ確認しました。完璧じゃないですか！！
とりあえず後はレイアウトをちょこまかいじっていこうと思います。
来週のスクールでいろいろ処理内容とか理解して行きたいと思います。ありがとうございます。

**Comment by omuomugin** [comment]
@yukiyuki961 
まあね笑
スクールで詳しく説明してあげる
